"""empty message

Revision ID: 43fa806a4f8b
Revises: None
Create Date: 2018-01-21 01:56:46.100097

"""

# revision identifiers, used by Alembic.
revision = '43fa806a4f8b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from config import Config
from sqlalchemy_utils import EncryptedType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Unicode(length=64), nullable=False),
    sa.Column('first_name', sa.Unicode(length=64), nullable=False),
    sa.Column('last_name', sa.Unicode(length=64), nullable=False),
    sa.Column('email', EncryptedType(sa.Unicode(length=64), Config.SECRET_KEY), nullable=False),
    sa.Column('phone', EncryptedType(sa.Unicode(length=64), Config.SECRET_KEY), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True),
    sa.Column('short_description', sa.Unicode(length=140), nullable=True),
    sa.Column('long_description', sa.UnicodeText(), nullable=True),
    sa.Column('education', sa.Enum('H', 'C', 'G', 'B', name='education_enum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('age_last_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_deleted_time', sa.DateTime(), nullable=True),
    sa.Column('password', EncryptedType(sa.Unicode(length=64), Config.SECRET_KEY), nullable=False),
    sa.Column('profile_photo', sa.Unicode(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True),
    sa.Column('education', sa.Enum('H', 'C', 'G', 'B', name='education_enum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
