"""empty message

Revision ID: 7ab6d2d4ad9f
Revises: ad04c5fe8f39
Create Date: 2018-01-07 21:37:12.058366

"""

# revision identifiers, used by Alembic.
revision = '7ab6d2d4ad9f'
down_revision = 'ad04c5fe8f39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo', sa.Unicode(length=140), nullable=True))
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_photo')
    # ### end Alembic commands ###
