"""empty message

Revision ID: ad04c5fe8f39
Revises: None
Create Date: 2018-01-01 17:22:11.245261

"""

# revision identifiers, used by Alembic.
revision = 'ad04c5fe8f39'
down_revision = None

from alembic import op
import sqlalchemy as sa
from config import Config
from sqlalchemy_utils import EncryptedType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Unicode(length=64), nullable=False),
    sa.Column('first_name', sa.Unicode(length=64), nullable=False),
    sa.Column('last_name', sa.Unicode(length=64), nullable=False),
    sa.Column('email', EncryptedType(sa.Unicode(64), Config.SECRET_KEY), nullable=False),
    sa.Column('phone', EncryptedType(sa.Unicode(64), Config.SECRET_KEY), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='gender_enum'), nullable=True),
    sa.Column('short_description', sa.Unicode(length=140), nullable=True),
    sa.Column('long_description', sa.UnicodeText(), nullable=True),
    sa.Column('education', sa.Unicode(length=64), nullable=True),
    sa.Column('estimated_age', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('age_last_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('password', EncryptedType(sa.Unicode(64), Config.SECRET_KEY), nullable=False),
    sa.Column('profile_picture', sa.Unicode(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
